
export const SEARCH_CODE="src/ERP/HR/Saga/Saga/SEARCH_CODE_SAGA"
export const SEARCH_COMPANY_CODE = "src/ERP/HR/Saga/Saga/SEARCH_COMPANY_CODE_SAGA"
export const SEARCH_WORK_PLACE_CODE = "src/ERP/HR/Saga/Saga/SEARCH_WORK_PLACE_CODE_SAGA"